# Generated by Django 3.2.9 on 2021-12-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('status', models.CharField(default='new', max_length=200, verbose_name='Статус')),
                ('date_todo', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
    ]
