# Generated by Django 3.2.9 on 2021-12-21 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_todo',
            new_name='date_done',
        ),
    ]
