# Generated by Django 3.2.9 on 2021-12-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_rename_title_task_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_done',
            new_name='date_deadline',
        ),
    ]
